---
title: "R Notebook"
output: html_notebook
---

```{r}
library(forecast)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(fpp2)
```



```{r}


data <- read.csv(file='./data/totais_diarios.csv')

y <- ts(data, start=1, end=113 + 4/7, frequency=7)


```

```{r}
length(y)
```

```{r}
plot(y)
```

```{r}
train <- window(y, start=c(2017,1), end= c(2018,365),frequency=365)
test <- window(y, start=c(2019,1), end=c(2019,59), frequency = 365)

```

```{r}

train <- window(y, start=1, end=105 + 1/7 ,frequency=7)
test <- window(y, start=105 + 2/7, end=113 + 4/7, frequency = 7)

```


```{r}
plot(train)
#plot(test)
```

```{r}
length(train)
length(test)
```
```{r}

autoplot(train)
```

```{r}
autoplot(test)
```
```{r}
library(EnvStats)
 train_after_boxcox = boxcox(as.numeric(train), objective.name = "Log-Likelihood", optimize = TRUE) 
```

```{r}
autoplot(train_after_boxcox)
```

```{r}
arima_fit <- auto.arima(train, approximation=FALSE , stepwise=FALSE)
```

```{r}
arima_fit_raw <- auto.arima(train)
```

```{r}
arima_fit
```

```{r}
arima_fit_raw
```



```{r}
checkresiduals(arima_fit)
```

```{r}
checkresiduals(arima_fit_raw)
```

```{r}
result_arima <- forecast(arima_fit,h = 7)
```

```{r}
result_arima_raw <- forecast(arima_fit_raw,h = 7)
```

```{r}
arima_fit
```

```{r}
accuracy(result_arima,test)
```

```{r}
accuracy(result_arima_raw,test)
```


```{r}
autoplot(test, series='test') +
  autolayer(result_arima, PI=FALSE, series="Arima results") +
  xlab("day") +
  ylab("Value") +
  ggtitle("Qty sell") +
  guides(colour=guide_legend(title="Forecast"))
```

```{r}
plot_start = 0
plot_end = 30
autoplot(ts(train[plot_start:plot_end]), series='treino') +
  autolayer(ts(fitted(result_arima)[plot_start:plot_end]),  series="Arima fitted values") +
  xlab("day") +
  ylab("Value") +
  ggtitle("Qty sell") +
  guides(colour=guide_legend(title="Forecast"))
```
```{r}
autoplot(test, series='test', shape=10) +
  autolayer(result_arima$mean,  series="Arima results") +
  xlab("day") +
  ylab("Value") +
  ggtitle("Qty sell") +
  guides(colour=guide_legend(title="Forecast"))
```


```{r}
#View dos valores de teste, forecasted e diferenças
test_matrix = as.matrix(test)
forecasted_matrix = as.matrix(result_arima$mean)
difference_test <- test_matrix - forecasted_matrix

test_table_difference = data.frame( test_matrix, forecasted_matrix, difference_test)

names(test_table_difference)[1] <- "teste"
names(test_table_difference)[2] <- "forecasted"
names(test_table_difference)[3] <- "diferença"

view(test_table_difference)
```

```{r}
#View dos valores de teste
train_matrix = as.matrix(train)
forecasted_matrix = as.matrix(fitted(result_arima))
difference_train <- train_matrix - forecasted_matrix

train_table_difference = data.frame( train_matrix, forecasted_matrix, difference_train)

names(train_table_difference)[1] <- "train"
names(train_table_difference)[2] <- "forecasted"
names(train_table_difference)[3] <- "diferença"

view(train_table_difference)
```


